# version: "3.9"
services:
  health-check:
    image: qma9/health-check
    build:
      context: .
      dockerfile: Dockerfile-health
    restart: "always"
    depends_on:
      auth:
        condition: service_started
  auth:
    image: qma9/auth
    build:
      context: .
      dockerfile: Dockerfile-auth
    restart: "always"
    ports:
      - "50051:50051"